### ISSUE TITLE
Beta channel switches to nightly

### ISSUE THREAD

**Issue by snomos** [divvun/pahkat#19]
<img width="557" alt="Skjermbilde 2021-11-08 kl  17 25 13" src="https://user-images.githubusercontent.com/1255285/140770053-1f6f71b0-6925-4c3f-bfc2-46208252b74c.png">

When selecing the `beta` channel, it automatically and immediately switches to `nightly`.

**Comment by bbqsrc** [comment]
Try in English?

**Comment by snomos** [comment]
> Try in English?

Didn't help - exactly the same behavior.

**Comment by snomos** [comment]
This is working as it should for me now, using the latest nightly build of DM.
